version: '3'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./programmer_library/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static

  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  web:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
