version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - programmer_library/programmer_library/.env.docker
    depends_on:
      - db
    command: >
      sh -c "
      python /code/programmer_library/manage.py migrate &&
      python /code/programmer_library/manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
