version: '3'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: peterpanda1/library_backend
    env_file: .env
    volumes:
      - static:/backend_static

  frontend:
    image: peterpanda1/library_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  web:
    image: peterpanda1/library_gateway
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static:/static
