# Generated by Django 3.2.15 on 2024-06-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
